### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by softmarshmallow** [soldair/node-qrcode#164]
> import QRCode from 'qrcode';

```
(function (exports, require, module, __filename, __dirname) { import QRCode from 'qrcode';
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
```

Using Flow

**Comment by soldair** [comment]
this project doesn't use es modules and it looks like its being evaluated in a script in a parse goal that doesn't support them.

it looks like you're compiling this into some kind of cjs bundle. let me know if you figure this out and anything i can do on my side to make it easier for folks in your spot.
