### ISSUE TITLE
Can't build in centos 7, got /bin/ld: cannot find -lusb-1.0

### ISSUE THREAD

**Issue by leadream** [soldair/node-qrcode#192]
## Env
CentOS Linux release 7.3.1611 (Core) 
Node v8.12.0
Yarn 1.15.2

## Behavior
I got below error when executing `yarn add qrcode`, can't figure it out. Can anyone help me? Thanks!

```
error /home/collecting.design/node_modules/node-hid: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/collecting.design/node_modules/node-hid
Output:
prebuild-install WARN install /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/collecting.design/node_modules/node-hid/build/Release/HID.node)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | linux | x64
gyp info spawn /bin/python2
gyp info spawn args [ '/root/nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/collecting.design/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/root/nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/collecting.design/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
make: 进入目录“/home/collecting.design/node_modules/node-hid/build”
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/hidapi/hidapi/linux/hid.o
  AR(target) Release/obj.target/hidapi.a
  COPY Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
  SOLINK_MODULE(target) Release/obj.target/HID.node
/bin/ld: cannot find -lusb-1.0
collect2: 错误：ld 返回 1
make: *** [Release/obj.target/HID.node] 错误 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "/root/nvm/versions/node/v8.12.0/bin/node" "/root/nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/collecting.design/node_modules/node-hid
gyp ERR! node -v v8.12.0
```

**Comment by soldair** [comment]
it looks like your install is failing on node-hid not qrcode at all.
```
make: 进入目录“/home/collecting.design/node_modules/node-hid/build”
```
node-hid is likely another dependency of your project. yarn is trying to build it every time you trigger a reinstall by installing anything.

maybe check https://www.npmjs.com/package/node-hid for info.

**Comment by leadream** [comment]
@soldair thanks, solved it.
I ran `yarn why node-hid` and found it's a dependency of [with-redux](https://www.npmjs.com/package/with-redux). Seems like it's being abused. Removing it can solve my problem.
