### ISSUE TITLE
Error using Uint8Array: input.charCodeAt is not a function

### ISSUE THREAD

**Issue by rhengles** [soldair/node-qrcode#231]
When using a Uint8Array object to create my qrcode:
```javascript
let data = [{ data: new Uint8Array([1,2,3,4,/*example*/5,6]), mode: 'byte' }]
QRCode.toCanvas(myCanvas, data, myOptions, function (error) {
	if (error) console.error(error);
	else console.log('QRCode drawn');
});
```

The library fails with the error below.
```
TypeError: input.charCodeAt is not a function
    at encodeUtf8 (qrcode.js:1417:25)
    at new ByteData (qrcode.js:1469:12)
    at buildSingleSegment (qrcode.js:1967:18)
    at qrcode.js:1992:20
    at Array.reduce (<anonymous>)
    at Object.fromArray (qrcode.js:1988:20)
    at createSymbol (qrcode.js:2393:29)
    at Object.create (qrcode.js:2493:12)
    at renderCanvas (qrcode.js:2708:25)
    at Proxy.fnRenderCode (qrcode.js:37:11)
```
I traced the error to the function below
```javascript
// path: /lib/core/byte-data.js
function ByteData (data) {
  this.mode = Mode.BYTE
  this.data = new Uint8Array(encodeUtf8(data)) // <-- error here
}
```
When I change it according to the code below, it works:
```javascript
// path: /lib/core/byte-data.js
function ByteData (data) {
  this.mode = Mode.BYTE
  if ('string' === typeof data) data = encodeUtf8(data)
  this.data = new Uint8Array(data)
}
```

**Comment by irvandikky** [comment]
In Node "[Buffer instances are also Uint8Array instances](https://nodejs.org/api/buffer.html#buffer_buffers_and_typedarray)", so data.toString() works in this case.

**Comment by air2** [comment]
Based on your finding I came to this (ugly) typescript work-around, because modifying the lib in  an existing project is of course a little bit problematic :

```
qr.segments.forEach(segment => {
  if (typeof segment.data !== 'string') {
    segment.data = decodeUtf8(segment.data)
  }
})
```
