### ISSUE TITLE
Generate qrcode with logo in the middle of the qr code

### ISSUE THREAD

**Issue by amarjeet045** [soldair/node-qrcode#248]
I am trying to create a qr code with logo in the middle and i have used one of the code given for the same type of question and i am using nodejs only and it gives an error 

here is the tried code can anybody try to help with this code 

const QRCode = require("qrcode");

const getQRcodeImage = async () => {
  try {
    let canvas = await QRCode.toCanvas(`my sample text`);

    //adding a log at center
    const imgDim = { width: 30, height: 30 }; //logo dimention
    var context = canvas.getContext("2d");
    var imageObj = new Image();
    imageObj.src = "./Capture.png";
    imageObj.onload = function () {
      context.drawImage(
        imageObj,
        canvas.width / 2 - imgDim.width / 2,
        canvas.height / 2 - imgDim.height / 2,
        imgDim.width,
        imgDim.height
      );
    };
    return canvas;
  } catch (e) {
    console.error(e);
    return "";
  }
};
getQRcodeImage();

Error: You need to specify a canvas element
    at getCanvasElement (/home/amarjeet/project/Backend/practiceCode/node_modules/qrcode/lib/renderer/canvas.js:17:11)
    at render (/home/amarjeet/project/Backend/practiceCode/node_modules/qrcode/lib/renderer/canvas.js:31:16)
    at /home/amarjeet/project/Backend/practiceCode/node_modules/qrcode/lib/browser.js:54:17
    at new Promise (<anonymous>)
    at renderCanvas (/home/amarjeet/project/Backend/practiceCode/node_modules/qrcode/lib/browser.js:51:12)
    at getQRcodeImage (/home/amarjeet/project/Backend/practiceCode/qrcode.js:5:31)
    at Object.<anonymous> (/home/amarjeet/project/Backend/practiceCode/qrcode.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by amarjeet045** [comment]
const QRCode = require("qrcode");
const { createCanvas, loadImage } = require("canvas");
async function create(dataForQRcode, center_image, width, cwidth) {
  const canvas = createCanvas(width, width);
  QRCode.toCanvas(canvas, dataForQRcode, {
    errorCorrectionLevel: "H",
    margin: 1,
    color: {
      dark: "#000000",
      light: "#ffffff",
    },
  });

  const ctx = canvas.getContext("2d");
  const img = await loadImage(center_image);
  const center = (width - cwidth) / 2;
  ctx.drawImage(img, center, center, cwidth, cwidth);
  return canvas.toDataURL("image/png");
}

async function main() {
  const qrCode = await create(
    "https://www.google.com/",
    "https://firebasestorage.googleapis.com/v0/b/growthfilepractice.appspot.com/o/Logo.png?alt=media&token=209b47f8-d10b-454d-bbfe-627c9a43da0a&fbclid=IwAR1LIIa8Jfcl_AJH4YvWauNVH1E-TQDQ6DNCPcQoTHK_qxPLqSb2I330jww",
    150,
    50
  );

  console.log(qrCode);
}

main();
