### ISSUE TITLE
Cannot provide integer array binary data with qrcode@1.5.0

### ISSUE THREAD

**Issue by cpetrov** [soldair/node-qrcode#289]
Segments with integer array data and `mode: "byte"` as [documented in the "Binary data" section of the README](https://www.npmjs.com/package/qrcode/v/1.5.0#binary-data) spawn an error with `qrcode@1.5.0`. This works as expected with the previous version `qrcode@1.4.4`.

```js
import QRCode from 'qrcode';

QRCode.toFile('foo.png', [{ data: [253, 254, 255], mode: 'byte' }]);
QRCode.toFile('foo.png', [{ data: new Uint8ClampedArray([253, 254, 255]), mode: 'byte' }]);
QRCode.toFile('foo.png', [{ data: Buffer.from([253, 254, 255]), mode: 'byte' }]);

// var point = input.charCodeAt(index)
// ^
//
// TypeError: input.charCodeAt is not a function
// at encodeUtf8 (/Users/cpetrov/git/my-proj/node_modules/encode-utf8/index.js:8:23)
// at new ByteData (/Users/cpetrov/git/my-proj/node_modules/qrcode/lib/core/byte-data.js:6:30)
// at buildSingleSegment (/Users/cpetrov/git/my-proj/node_modules/qrcode/lib/core/segments.js:262:14)
// at /Users/cpetrov/git/my-proj/node_modules/qrcode/lib/core/segments.js:286:16
// at Array.reduce (<anonymous>)
// at Object.fromArray (/Users/cpetrov/git/my-proj/node_modules/qrcode/lib/core/segments.js:282:16)
// at createSymbol (/Users/cpetrov/git/my-proj/node_modules/qrcode/lib/core/qrcode.js:382:25)
// at Object.create (/Users/cpetrov/git/my-proj/node_modules/qrcode/lib/core/qrcode.js:494:10)
// at /Users/cpetrov/git/my-proj/node_modules/qrcode/lib/server.js:71:29
// at new Promise (<anonymous>)
```

**Comment by Arno500** [comment]
I can confirm I also experience this issue

**Comment by RSLak1** [comment]
Also experiencing this issue.
Following the stacktrace, I believe the issue would be that in `byte-data.js` the class `ByteData` expects a string, but is passed the already existing byte array from `buildSingleSegment` in `segment.js`.
