### ISSUE TITLE
False positive : The amount of data is too big to be stored in a QR Code

### ISSUE THREAD

**Issue by lk77** [soldair/node-qrcode#293]
Hello,

i get random errors like that :

```
Error: The amount of data is too big to be stored in a QR Code
    at createSymbol (qrcode.js:410:11)
    at Object.create (qrcode.js:499:10)
    at renderCanvas (browser.js:62:23)
```

```
QRCode.toDataURL('test')
```

sometimes it works, sometimes it don't, it seems related to the getCapacity function, which sometimes return NaN

![Capture d’écran du 2022-01-11 16-10-43](https://user-images.githubusercontent.com/9606882/148968484-0e449869-adf3-4293-b830-8bcb265698e7.png)

if you have any idea why,

thanks !

**Comment by soldair** [comment]
Interesting thanks for the report

**Comment by chethanyadav456** [comment]
I have the same problem , any fix ?
![image](https://github.com/soldair/node-qrcode/assets/46392684/342e47c7-baae-4133-952d-b1523d57a974)

**Comment by Kucerenko171** [comment]
> I have the same problem , any fix ? ![image](https://private-user-images.githubusercontent.com/46392684/293064729-342e47c7-baae-4133-952d-b1523d57a974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNDY5MjEsIm5iZiI6MTcyODA0NjYyMSwicGF0aCI6Ii80NjM5MjY4NC8yOTMwNjQ3MjktMzQyZTQ3YzctYmFhZS00MTMzLTk1MmQtYjE1MjNkNTdhOTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDEyNTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMTg1Y2EyNzMyNDQzYWNjY2M1YjVjNjIxYTk4ZGMxYWM3NDQxMGRjNGQ1YmQyY2U3YTgyY2NhMTA5MDBhYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.30zNB-scl8EgkKmngvPFztpPyH0PizAqr07PV6Bl4lA)


How could you solve this problem?

**Comment by chethanyadav456** [comment]
> > I have the same problem , any fix ? ![image](https://private-user-images.githubusercontent.com/46392684/293064729-342e47c7-baae-4133-952d-b1523d57a974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNDY5MjEsIm5iZiI6MTcyODA0NjYyMSwicGF0aCI6Ii80NjM5MjY4NC8yOTMwNjQ3MjktMzQyZTQ3YzctYmFhZS00MTMzLTk1MmQtYjE1MjNkNTdhOTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDEyNTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMTg1Y2EyNzMyNDQzYWNjY2M1YjVjNjIxYTk4ZGMxYWM3NDQxMGRjNGQ1YmQyY2U3YTgyY2NhMTA5MDBhYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.30zNB-scl8EgkKmngvPFztpPyH0PizAqr07PV6Bl4lA)
> 
> How could you solve this problem?

you have to have short amount of data. better to make a endpoint to the data and In QR code data add the link. simple
