### ISSUE TITLE
tying to run this in Lambda, throws the error:

### ISSUE THREAD

**Issue by TrustyBytes** [soldair/node-qrcode#301]
tying to run this in Lambda, throws the error:

 {"errorType":"TypeError","errorMessage":"Cannot read property 'bind' of undefined","trace":["TypeError: Cannot read property 'bind' of undefined","    at Object.toFileStream (/var/task/node_modules/qrcode/lib/server.js:133:52)","    at Runtime.module.exports.getCertificateQRCode [as handler] (/var/task/handler.js:40:11)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}

` 
 module.exports.getQRCode = async (event) => {     
   const response = {headers: {"content-type": "image/png"},};
   qrcode.toFileStream(response, "whateverstring");
   return response;
 };
`

I did confirm your code works in a simple http server.

It also works in express.  It seems it has trouble when it is running from an exported module....

_Originally posted by @fhirfly in https://github.com/soldair/node-qrcode/issues/168#issuecomment-805812186_

**Comment by TrustyBytes** [comment]
`	QRCode.toFileStream(`${orderId}.png`, rouletteUrl, (err, data) => {
		if (err) {
			console.error(err);
			return res.json({ err });
		}
	});`

Response : TypeError: Cannot read properties of undefined (reading 'bind'). Even when running locally

**Comment by soldair** [comment]
Are you perhaps using the browser bundle rather than the server one?
