### ISSUE TITLE
"You need to specify a canvas element" error when using Cloudflare Workers with `qrcode`

### ISSUE THREAD

**Issue by bkyerv** [soldair/node-qrcode#349]
I am encountering an error when attempting to generate a QR code using the qrcode library within a Cloudflare Worker. The error message is "You need to specify a canvas element".

Error stack:
```
Error: You need to specify a canvas element
    at getCanvasElement (index.js:2058:15)
    at Object.render (index.js:2069:20)
    at renderToDataURL (index.js:2088:32)
    at renderCanvas (index.js:2214:18)
    at qr (index.js:2307:31)
    at new Promise (<anonymous>)
    at Object.fetch (index.js:2306:24)
    at async jsonError (index.js:2337:12) {
  stack: Error: You need to specify a canvas element
    at…306:24)
    at async jsonError (index.js:2337:12),
  message: You need to specify a canvas element
}
```
Environment:

    Using Cloudflare Workers.
    Implementing the server API of the qrcode library.

Steps to Reproduce:

    Set up a Cloudflare Worker.
    Integrate the qrcode library to generate a QR code.
    Execute the worker function to generate the QR code.

Expected Result:
The QR code should be generated successfully.

Actual Result:
Encountering the above error, which seems to suggest a canvas element is required.

I would appreciate any guidance or suggestions on how to resolve this issue, especially considering the context of using Cloudflare Workers where a DOM-based canvas isn't available.

Thank you!

Below is the source code for the worker

```
export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		
		if (request.method !== 'POST') {
			return new Response('Method not allowed', { status: 405 });
		}

		try {
			const payload = await request.json();
			
			const qr = await QRCode.toDataURL(payload.uniqueTitle, { type: 'image/webp' });
			
                        return new Response(qr);

		} catch (e) {
			console.error(e);
			return new Response(null, { status: 500});
		}
	},
};

```

**Comment by lexakozakov** [comment]
same here

**Comment by kamil-homernik** [comment]
I'm also looking for a solution to generate QR codes without access to DOM

**Comment by feri-irawan** [comment]
Try using node-canvas

**Comment by evanoxu** [comment]
same here

**Comment by techieshark** [comment]
Not a fix for this library, but if anyone is desperate here might be some leads

* https://github.com/naptestdev/qr-code-cloudflare-worker
* https://github.com/imbytecat/qr-code-worker
* https://github.com/rikkaneko/qrcode-gen

**Comment by abusedmedia** [comment]
A solution is just using `QRCode.toString` instead of `QRCode.toDataURL`. 
You'll get an SVG instead of a PNG. Good enough for many cases.

**Comment by fmchisti** [comment]
I’ve created a version that works well with both Cloudflare and TypeScript.



```


import QRCode from "qrcode";

export interface QrCodeSvgOptions {
  moduleSize?: number;
  foregroundColor?: string;
  backgroundColor?: string;
  padding?: number;
  crispEdges?: boolean;
  errorCorrectionLevel?: "L" | "M" | "Q" | "H";
  qrVersion?: number;
}

export function renderQrCodeMatrixToSvg(
  dataMatrix: boolean[][],
  options?: QrCodeSvgOptions,
): string {
  const moduleSize = options?.moduleSize ?? 5;
  const foregroundColor = options?.foregroundColor ?? "#000000";
  const backgroundColor = options?.backgroundColor ?? "#FFFFFF";
  const padding = options?.padding ?? moduleSize;
  const crispEdges = options?.crispEdges ?? true;

  if (!dataMatrix || dataMatrix.length === 0) {
    const errorMsg = "No QR Data";
    const errWidth = errorMsg.length * 8 + 20;
    const errHeight = 40;
    return `<svg width="${errWidth}" height="${errHeight}" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="${errWidth}" height="${errHeight}" fill="#FFF0F0" stroke="#D00000" stroke-width="1"/><text x="${errWidth / 2}" y="${errHeight / 2}" font-family="sans-serif" font-size="10" fill="#D00000" text-anchor="middle" dominant-baseline="middle">${errorMsg}</text></svg>`;
  }

  const numRows = dataMatrix.length;
  const numCols = dataMatrix[0]?.length ?? 0;
  const qrCodeContentWidth = numCols * moduleSize;
  const qrCodeContentHeight = numRows * moduleSize;
  const svgWidth = qrCodeContentWidth + 2 * padding;
  const svgHeight = qrCodeContentHeight + 2 * padding;

  let svgString = `<svg width="${svgWidth}" height="${svgHeight}" viewBox="0 0 ${svgWidth} ${svgHeight}" xmlns="http://www.w3.org/2000/svg"`;
  if (crispEdges) {
    svgString += ` shape-rendering="crispEdges"`;
  }
  svgString += `>`;

  if (backgroundColor && backgroundColor.toLowerCase() !== "transparent") {
    svgString += `<rect x="0" y="0" width="${svgWidth}" height="${svgHeight}" fill="${backgroundColor}" />`;
  }

  svgString += `<g transform="translate(${padding}, ${padding})">`;
  for (let r = 0; r < numRows; r++) {
    for (let c = 0; c < numCols; c++) {
      if (dataMatrix[r][c]) {
        const x = c * moduleSize;
        const y = r * moduleSize;
        svgString += `<rect x="${x}" y="${y}" width="${moduleSize}" height="${moduleSize}" fill="${foregroundColor}" />`;
      }
    }
  }
  svgString += `</g></svg>`;
  return svgString;
}

export function generateScannableQrCodeSvg(
  textToEncode: string,
  options?: QrCodeSvgOptions,
): string {
  const eclOption = options?.errorCorrectionLevel ?? "M";
  let libEcl: "low" | "medium" | "quartile" | "high";
  switch (eclOption) {
    case "L":
      libEcl = "low";
      break;
    case "M":
      libEcl = "medium";
      break;
    case "Q":
      libEcl = "quartile";
      break;
    case "H":
      libEcl = "high";
      break;
    default:
      libEcl = "medium";
  }

  const qrOptions: QRCode.QRCodeOptions = {
    errorCorrectionLevel: libEcl,
  };

  if (options?.qrVersion && options.qrVersion > 0 && options.qrVersion <= 40) {
    qrOptions.version = options.qrVersion;
  }

  try {
    const qrCodeInstance = QRCode.create(textToEncode, qrOptions);
    const size = qrCodeInstance.modules.size;
    const qrData = qrCodeInstance.modules.data;
    const dataMatrix: boolean[][] = [];

    for (let r = 0; r < size; r++) {
      dataMatrix[r] = [];
      for (let c = 0; c < size; c++) {
        dataMatrix[r][c] = qrData[r * size + c] === 1;
      }
    }
    return renderQrCodeMatrixToSvg(dataMatrix, options);
  } catch (error) {
    console.error("Error generating QR code with 'qrcode' library:", error);
    if (
      error instanceof Error &&
      error.message.includes("Cannot find module 'qrcode'")
    ) {
      const errorMsg = "QR Library Missing";
      const detailMsg = "Run: npm install qrcode";
      const errWidth = detailMsg.length * 7 + 20;
      const errHeight = 60;
      return `<svg width="${errWidth}" height="${errHeight}" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="${errWidth}" height="${errHeight}" fill="#FFF0F0" stroke="#D00000" stroke-width="1"/><text x="${errWidth / 2}" y="25" font-family="sans-serif" font-size="12" fill="#D00000" text-anchor="middle">${errorMsg}</text><text x="${errWidth / 2}" y="45" font-family="sans-serif" font-size="9" fill="#D00000" text-anchor="middle">${detailMsg}</text></svg>`;
    }

    const errorMsg = "QR Gen Error";
    const errWidth = errorMsg.length * 8 + 20;
    const errHeight = 40;
    return `<svg width="${errWidth}" height="${errHeight}" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="${errWidth}" height="${errHeight}" fill="#FFF0F0" stroke="#D00000" stroke-width="1"/><text x="${errWidth / 2}" y="${errHeight / 2}" font-family="sans-serif" font-size="10" fill="#D00000" text-anchor="middle" dominant-baseline="middle">${errorMsg}</text></svg>`;
  }
}
```
