### ISSUE TITLE
not compiling with the latest node version (5.9.1)

### ISSUE THREAD

**Issue by sagivo** [soldair/node-qrcode#47]
```
npm install qrcode

> canvas@1.3.12 install /Users/sagivo/dev/work/rbi/qr/node_modules/canvas
> node-gyp rebuild

Package xcb-shm was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-shm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xcb-shm', required by 'cairo', not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/sagivo/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Users/sagivo/.nvm/versions/node/v5.9.1/bin/node" "/Users/sagivo/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sagivo/dev/work/rbi/qr/node_modules/canvas
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN qr@1.0.0 No repository field.
npm WARN qr@1.0.0 No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/sagivo/.nvm/versions/node/v5.9.1/bin/node" "/Users/sagivo/.nvm/versions/node/v5.9.1/bin/npm" "install" "qrcode"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sagivo/dev/work/rbi/qr/npm-debug.log
sagiv:qr sagivo$

```

**Comment by throrin19** [comment]
Have you read this? : 

>Package xcb-shm was not found in the pkg-config search path.
>Perhaps you should add the directory containing `xcb-shm.pc' to the PKG_CONFIG_PATH environment variable
>Package 'xcb-shm', required by 'cairo', not found

The error is not an qrcode compilation error but a *cairo* compilation error. You are missing a dependency : *xcb-shm*.

After search i found an issue here : https://github.com/Homebrew/homebrew/issues/14123

**Comment by soldair** [comment]
thanks for the advice @throrin19! happy y'all got this resolved =)
