### ISSUE TITLE
unable to install with NPM

### ISSUE THREAD

**Issue by jwerre** [soldair/node-qrcode#55]
I'm getting the following error at install:

```
npm install qrcode
-
> canvas@1.3.16 install /Users/me/myproject/node_modules/qrcode/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/myproject/node_modules/qrcode/node_modules/canvas
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "qrcode"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.16 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/myproject/npm-debug.log
```

I'm on OSX 10.12 (Sierra), Node 4.4.4, npm 2.15.1
any ideas?

**Comment by desaias** [comment]
Have you followed the instructions on the installation of [canvas](https://github.com/Automattic/node-canvas)?

I was having this issue too and canvas requires you to `brew install pkg-config cairo libpng jpeg giflib` first.  This has worked for me, but as a heads up... it takes a while.

**Comment by soldair** [comment]
i'm sure @desaias suggestion is correct. if you resolve you abillity to install node-canvas thi'll install great.

one day i hope to remove canvas as a dep adn rely on js image encoders
